services:
  - type: web
    name: portfoliodjango
    env: python
    buildCommand: "pip install -r requirements.txt && npm install bulma"
    startCommand: "gunicorn portfoliodjango.wsgi:application"
    healthCheckPath: /