# Generated by Django 5.0.2 on 2024-02-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('data_category', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=150)),
                ('language_framework', models.CharField(max_length=150)),
                ('client', models.CharField(max_length=100)),
                ('preview', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('card_img_url', models.URLField()),
                ('modal_img_url', models.URLField()),
            ],
        ),
    ]
