# Generated by Django 5.0.2 on 2024-02-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='short_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='data_category',
            field=models.CharField(default='web', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='language_framework',
            field=models.CharField(default='HTML, CSS, JavaScript', max_length=150),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
