# Generated by Django 5.0.2 on 2024-02-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_case_short_description_alter_case_data_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='preview_url',
            field=models.URLField(default='https://spindola.engineer'),
        ),
        migrations.AlterField(
            model_name='case',
            name='custom_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='language_framework',
            field=models.CharField(default='HTML, CSS, JavaScipt', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='short_description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
